### ISSUE TITLE
Feature Request: Add TTS Generation (Single and Multi-Speaker) to LLMFlow

### ISSUE THREAD

**Issue by jonathanrobie** [nida-institute/LLMFlow#12]
## Description

Add a text-to-speech (TTS) stage to LLMFlow using **SIL AERO**.
Support both:

* Single voice per text
* Multiple voices within a text (speaker changes)

TTS output should generate `.wav` audio files. Multi-speaker texts must stitch different voice outputs into a single audio file.

---

## Requirements

* [ ] Add `generate_audio` for single-voice text input.
* [ ] Add `generate_audio_multi_speaker` for multi-voice text input.
* [ ] Allow specifying language, voice, and (optional) speech rate.
* [ ] Support speaker → voice mapping.
* [ ] Use SIL AERO locally or via API.
* [ ] Output `.wav` files named by `slug`.

Example inputs:

```yaml
# Single speaker
text: "Hello, welcome!"
speaker_id: "narrator"
slug: "intro"

# Multi-speaker
text_blocks:
  - speaker: narrator
    text: "Welcome!"
  - speaker: guest
    text: "Thank you."
slug: "scene1"
```

---

## Notes

* Prefer minimal dependencies (e.g., `pydub` for audio stitching).
* Log voice usage and raise errors for missing voices.
* Future: support timestamps and variable speech rates.
