### ISSUE TITLE
Linter: Check Markdown/HTML Templates for Missing `{variables}`

### ISSUE THREAD

**Issue by jonathanrobie** [nida-institute/LLMFlow#15]
### 📝 Description:

The current linter checks `.gpt` prompts for required variables, but does **not** validate `{variables}` used in Markdown or HTML templates (like `exegeticalguide_template.md`). This can lead to runtime surprises like:

```html
<h1>Exegetical Guide for {MISSING:passage}</h1>
```

We should extend the linter to scan templates for unbound `{variables}` and ensure they’re included in the pipeline step’s `variables:` block.

---

### 🛠 Tasks

* [ ] In `linter.py`, detect steps of type `function` where `function = render_markdown_template`
* [ ] Load the template file from `inputs.template_path`
* [ ] Extract all `{variable}` placeholders in the template
* [ ] Compare those to `inputs.variables` for that step
* [ ] Emit `❌ Missing variable '...' for template ...` if a mismatch is found

---

### 📦 Example

Given this step:

```yaml
- name: render_exegetical_markdown
  function: llmflow.utils.io.render_markdown_template
  inputs:
    template_path: templates/exegeticalguide_template.md
    variables:
      culture: "${exegetical_culture}"
```

And this in the template:

```markdown
# Guide for {passage}
```

The linter should raise:

```
❌ render_exegetical_markdown is missing required template variable 'passage' (used in templates/exegeticalguide_template.md)
```
