### ISSUE TITLE
 Inject Persona Information at Runtime for Each LLM Step

### ISSUE THREAD

**Issue by jonathanrobie** [nida-institute/LLMFlow#6]
Implement dynamic persona injection into LLM prompts at runtime for each llm pipeline step in LLMFlow. When a step specifies a persona:, lookup the description from /config/personas.yaml (loaded once at startup) and prepend it to the prompt before sending it to the LLM. This ensures each output matches the intended audience tone without requiring manual changes to prompts or a separate build step.

**Comment by jonathanrobie** [comment]
## SUPERSEDED

Runtime persona injection has been **replaced by variable resolution and prompt templates**:

Current approach:
- Variables passed via `--var` CLI flag or `vars:` in YAML
- Prompt templates use `{{variable}}` syntax
- Step-level `system:` field for persona/role definition
- More explicit, auditable, and testable than implicit persona injection

See example:
```yaml
steps:
  - name: analyze
    model: gpt-4o
    system: "You are a biblical Greek scholar analyzing syntax."
    prompt:
      file: analyze.gpt
```
